### ISSUE TITLE
Found no NVIDIA driver on your system.

### ISSUE THREAD

**Issue by twfqkhws** [MathiasHaudgaard/reflex_behaviour#1]
I do not have a GPU is it possible to still run the simulator
![image](https://user-images.githubusercontent.com/56922394/78674752-03327c80-78dc-11ea-88ff-75f7707576c7.png)

**Comment by MathiasHaudgaard** [comment]
Thanks for letting me know 👍 
I've fixed the issue and it should now support CPU as well for testing.
I'll fix the CPU support for the training part tomorrow. 
Just be aware of performance issues when using a CPU. I tried on my pc and it has a tough time keeping up with the car simulation.

**Comment by twfqkhws** [comment]
Thank you so much for the reply I got it to work with cpu
