### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by raduwolf12** [MathiasHaudgaard/reflex_behaviour#2]
I have created the environment as in descriprion.
I have run the "python drive.py models/model_50000" comand in Anaconda Prompt.
![image](https://user-images.githubusercontent.com/45209751/103443343-05591a00-4c67-11eb-92b6-a66ecc54a6c1.png)
After this nothing is happening. I did not receive a connected message. 
I tried  using both Version 2 and Version 1 simulator from Term 1 from the audacity git repo(https://github.com/udacity/self-driving-car-sim).
Can you help me find what is going on ?

**Comment by AnukritiSinghh** [comment]
I have the same issue. Did you find any solution?

**Comment by MathiasHaudgaard** [comment]
Hi, sorry for the late answer. It seems to be a problem with the newer versions of python-socketio. If you downgrade the package to 4.2.1 it should work. Just pip install python-socketio==4.2.1
I'll update the environments.yml file so it matches the correct version

**Comment by MathiasHaudgaard** [comment]
I have updated the dependencies so if you pull and run conda env create -f environments.yml it should work.

**Comment by raduwolf12** [comment]
Thank you very much for the advice, it works now.
