### ISSUE TITLE
cv2 Error

### ISSUE THREAD

**Issue by AnukritiSinghh** [MathiasHaudgaard/reflex_behaviour#3]
In program `train.py` I have error in line number 41 (`img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)`) the error says :  
`cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-1syr35c1/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'`
The line before this in the code is `img = cv2.imread(data[img_pth])` When I try to print(data[img_pth]) I see correct path getting printed but ehn I print(img) after this line I get `none` 
Can you please help me solve this problem?

**Comment by MathiasHaudgaard** [comment]
I can reproduce the error. However, I have not been able to solve it yet. It seems like it only happens on some images but not all of them. I'm looking further into this

**Comment by AnukritiSinghh** [comment]
Thanks! Please let me know if you find a way

**Comment by ernerdgn** [comment]
You'll get the error `error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'` if the img path is empty.
I was getting the same error, check your 'driving_log.csv' file. I got my [data](https://www.kaggle.com/zaynena/selfdriving-car-simulator) from kaggle. IMG paths were 'Desktop\track1data' or 'Desktop\track2data', i changed them to correct paths that i put the images.

**Comment by MathiasHaudgaard** [comment]
@ernerdgn I'm aware that the problem comes from the empty image path. However, I'm not sure why it doesn't accept the img path.
```python
print(f'path {data[img_pth]}')
print(f'path {type(data[img_pth])}')
img = cv2.imread(data[img_pth])
print(f'img {img}')
print(type(img))
```
results to
```
path  C:\\Users\\Mathi\\reflex_behaviour\\hello\\IMG\\left_2021_04_28_22_53_41_951.jpg
path <class 'str'>
img None
<class 'NoneType'>
```

I've tried using \\\ and \ and / for the img path but nothing works.
However, if I input a static string in cv2.imread
```python
img = cv2.imread(" C:\\Users\\Mathi\\reflex_behaviour\\hello\\IMG\\left_2021_04_28_22_53_41_951.jpg")
```
it works. I hope someone can help me fix the issue :shipit:

**Comment by MathiasHaudgaard** [comment]
@AnukritiSinghh can you send one row from your CSV file?

**Comment by MathiasHaudgaard** [comment]
The error came from invalid paths in the csv file. You should be able to train your model :shipit:
